### PR TITLE
Add roketo stream function call template

### PR DESCRIPTION
**Pull request by sergeysova**

### CODE REVIEW

**Review by VERZUOL1 — DISMISSED** [review]

**Comment by VERZUOL1** [comment]
Could you please hide this feature visibility under feauter flag? We use launchdarkly service to toggle it on/off.
You can find usage examples in the app like:
`
const { cfcLibrary } = useFlags();

...

return (
  {cfcLibrrary && (
     _...some content_
  )}

)
`

**Comment by sergeysova** [comment]
@VERZUOL1 How can I enable my new `roketoStreaming` flag for development purpose?

**Review by VERZUOL1 — APPROVED** [review]

**Comment by VERZUOL1** [comment]
I have enabled it on dev instance for you!

**Comment by sergeysova** [comment]
@VERZUOL1 
image

Do I have to change something in my configs to enable this flag?

**Pull request merged**
